### ISSUE TITLE
Unknown parameter in input: "registeredAt"

### ISSUE THREAD

**Issue by MoJo2600** [silinternational/ecs-deploy#219]
There seems to be a change on AWS side, since yesterday the deployment fails with this message:

```bash
Creating new task definition revision
Traceback (most recent call last):
  File "/usr/bin/ecs", line 11, in <module>
    load_entry_point('ecs-deploy==1.11.0', 'console_scripts', 'ecs')()
  File "/usr/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/ecs_deploy/cli.py", line 95, in deploy
    new_td = create_task_definition(deployment, td)
  File "/usr/lib/python2.7/site-packages/ecs_deploy/cli.py", line 481, in create_task_definition
    new_td = action.update_task_definition(task_definition)
  File "/usr/lib/python2.7/site-packages/ecs_deploy/ecs.py", line 628, in update_task_definition
    additional_properties=task_definition.additional_properties
  File "/usr/lib/python2.7/site-packages/ecs_deploy/ecs.py", line 86, in register_task_definition
    **additional_properties
  File "/usr/lib/python2.7/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/lib/python2.7/site-packages/botocore/client.py", line 649, in _make_api_call
    api_params, operation_model, context=request_context)
  File "/usr/lib/python2.7/site-packages/botocore/client.py", line 697, in _convert_to_request_dict
    api_params, operation_model)
  File "/usr/lib/python2.7/site-packages/botocore/validate.py", line 297, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Unknown parameter in input: "registeredAt", must be one of: family, taskRoleArn, executionRoleArn, networkMode, containerDefinitions, volumes, placementConstraints, requiresCompatibilities, cpu, memory, tags, pidMode, ipcMode, proxyConfiguration, inferenceAccelerators
Unknown parameter in input: "registeredBy", must be one of: family, taskRoleArn, executionRoleArn, networkMode, containerDefinitions, volumes, placementConstraints, requiresCompatibilities, cpu, memory, tags, pidMode, ipcMode, proxyConfiguration, inferenceAccelerators
```

Somebody [at Atlassian](https://community.atlassian.com/t5/Bitbucket-Pipelines-questions/Pipeline-failing-Unknown-parameter-in-input-quot-registeredAt/qaq-p/1585076) has the same error, so I don't think it is related to this library.

Maybe there is a way to circumvent this issue, maybe by removing the parameter `registeredAt` and `registeredBy`?

Best Christian

**Comment by MoJo2600** [comment]
Sorry, wrong project :)
